apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carwashapp.name" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "carwashapp.name" . }}
    helm.sh/chart: {{ include "carwashapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  POSTGRES_PASSWORD: aXNzYm90dGVzdA==
