kind: Service
apiVersion: v1
metadata:
  name: carwash-external
spec:
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: carwash

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: carwash-external-ingress
spec:
  routes:
    - kind: Rule
      match: Host(`carwashapp.local`)
      priority: 10
      services:
        - name: carwash-external
          passHostHeader: True
          port: 8080