kind: ConfigMap
apiVersion: v1
metadata:
  name: carwash-env-db
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  POSTGRES_DB: "carwash"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "testpassword"
  DB_ENGINE: django.db.backends.postgresql
  DEBUG: 'False'
  ALLOWED_HOST: 'carwashapp.local'
  
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configmap
data:
  ucr-app.conf: |
    upstream app_server {
      server 127.0.0.1:8000 fail_timeout=0;
    }

    server {
      listen 8080;
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name carwashapp.local;

      access_log /var/log/nginx/access.log combined;
      error_log  /var/log/nginx/error.log warn;

      keepalive_timeout 5;

      # path for static files (only needed for serving local staticfiles)
      location /static/ {
          alias /src/static_root/;
      }

      location = /favicon.ico { access_log off; log_not_found off; }

      location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
      }

      location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_redirect off;
        proxy_pass http://app_server;
      }

      error_page 500 502 503 504 /500.html;
      location = /500.html {
        root /src/;
      }
    }