apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgresql-db
spec:
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql-db
