apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  serviceName: postgresql-db-service
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: db
          image: postgres:latest

          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: carwash-env-db
      volumes:
        - name: postgresql-db-disk
          persistentVolumeClaim:
            claimName: postgres-pv-claim
  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgresql-db-disk
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi