apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  serviceName: postgresql-db-service
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: db
          image: postgres:latest

          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          envFrom:
            - configMapRef:
                name: carwash-env-db
          # env:
            # - name: PGDATA
            #   value: /data/pgdata
            # - name: POSTGRESQL_LOG_HOSTNAME
            #   value: "true"
            # - name: POSTGRESQL_LOG_CONNECTIONS
            #   value: "false"
            # - name: POSTGRESQL_LOG_DISCONNECTIONS
            #   value: "false"
            # - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
            #   value: "off"
            # - name: POSTGRESQL_CLIENT_MIN_MESSAGES
            #   value: "error"
            # - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
            #   value: "pgaudit, repmgr"
            # - name: POSTGRESQL_ENABLE_TLS
            #   value: "no"
      # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi