# Generated by Django 4.1 on 2022-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(default='smtp.google.com', max_length=64)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='name@company.com', max_length=128)),
                ('smtp_password', models.CharField(blank=True, default='password', max_length=256)),
            ],
        ),
    ]
