# Generated by Django 4.1 on 2022-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='smtp_body',
            field=models.TextField(blank=True, default='Default Body Field', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='smtp_protocol',
            field=models.CharField(choices=[('STLS', 'STARTTLS'), ('TLS', 'TLS'), ('NONE', 'NONE')], default='STLS', max_length=4),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='smtp_subject',
            field=models.CharField(blank=True, default='Default E-Mail Subject Title', max_length=64),
        ),
    ]
