# Generated by Django 4.1 on 2022-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_emailsettings_smtp_body_emailsettings_smtp_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_subject',
            field=models.TextField(blank=True, default='Default E-Mail Subject Title', max_length=64),
        ),
    ]
