# Generated by Django 4.1 on 2022-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_emailsettings_smtp_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_subject',
            field=models.CharField(blank=True, default='Default E-Mail Subject Title', max_length=64),
        ),
    ]
