# Generated by Django 4.1 on 2022-09-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_emailsettings_smtp_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(default='client_id', max_length=128)),
                ('auth_token', models.CharField(default='token', max_length=128)),
                ('message_sid', models.CharField(blank=True, default='message_id', max_length=128)),
                ('country_code', models.IntegerField(default=46, max_length=4)),
                ('phonenumber', models.IntegerField(max_length=24)),
                ('body', models.TextField(blank=True, default='Default Body Field', max_length=255)),
            ],
        ),
    ]
