# Generated by Django 4.1 on 2022-08-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_work_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='complete',
            new_name='completed',
        ),
    ]
