# Generated by Django 4.1 on 2022-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_complete_work_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='email_address',
            field=models.CharField(blank=True, default='name@company.com', max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='phonenumber',
            field=models.CharField(blank=True, default='070111222', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='sms_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(blank=True, default='Tvätt', max_length=128),
        ),
    ]
