# Generated by Django 4.1 on 2022-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_work_email_address_work_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, default='In queue', max_length=16),
        ),
    ]
