# Generated by Django 4.1 on 2022-09-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_work_started_alter_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
